import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProd = process.argv[2] === 'production';

const context = await esbuild.context({
	entryPoints: ['main.ts'],
	bundle: true,
	external: ['obsidian'],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: isProd ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	// 移除 watch 选项，或者根据环境变量来决定是否使用
	...(isProd ? {} : { watch: true })
});

if (isProd) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
